set number
set hls
set tabstop=4 shiftwidth=4 expandtab

" Mapping keys
map <F2> :NERDTreeToggle<CR>
map <F3> :MerginalToggle<CR>

call plug#begin('~/.vim/plugged')

Plug 'idanarye/vim-merginal'
Plug 'jiangmiao/auto-pairs'
Plug 'scrooloose/syntastic'
Plug 'yggdroot/indentline'
Plug 'mhartington/oceanic-next'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

colorscheme OceanicNext 

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"


