" Setting defaults
set number
set hls
set tabstop=4 shiftwidth=4 expandtab

" Install plugins with vim-plug
call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'idanarye/vim-merginal'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'yggdroot/indentline'
Plug 'jiangmiao/auto-pairs'
Plug 'joshdick/onedark.vim'
Plug 'dracula/vim', { 'as': 'dracula'  }
Plug 'ap/vim-css-color'
Plug 'valloric/youcompleteme'
Plug 'ryanoasis/vim-devicons'

call plug#end()

" Modify Vim Color Layout
colorscheme dracula
hi Normal guibg=NONE ctermbg=NONE
" Key Mappings
nmap <C-t> :NERDTreeToggle<CR>
nmap <C-b> :MerginalToggle<CR>
" Statusline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
  
